name: Push main

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  build-and-push:
    needs: [tests]
    runs-on: ubuntu-latest
    outputs:
      image-id: ${{ steps.build.outputs.image-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - uses: cern-sis/gh-workflows/.github/actions/docker-build@v7.0.0
        id: build
        with:
          image: cern-sis/inspire/inspirehep-mcp
          stage: prod
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
          push: true
          cache: false
          registry: registry.cern.ch
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}

  dispatch-image-update:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v7.0.0
        with:
          event-type: update
          repo: cern-sis/kubernetes-inspire
          images: |
            cern-sis/inspire/inspirehep-mcp${{ needs.build-and-push.outputs.image-id }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
